### ISSUE TITLE
conda install lynx forced a downgrade of Python and broke Pandas

### ISSUE THREAD

**Issue by mike-suplari** [conda-forge/lynx-feedstock#3]
As the title says, `conda install lynx` with conda-forge enabled downgraded Python and broke Pandas. I uninstalled lynx and it fixed the problem.

**Comment by epruesse** [comment]
The 2.8.9 should work with a current python. I'm not sure why the two interfere, but it's not really `lynx` that was broken there, but some missing dependencies that allowed mismatching versions of python and pandas to be installed.

If you observe things like that - post it on the conda-forge gitter channel. There are almost always core devs over there who can help and also fix this for others.
